language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

matrix:
    include:
        - php: 5.3
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    allow_failures:
        - php: 7.0

env:
    - SYMFONY_VERSION="2.*"

install:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - vendor/bin/phpunit
